temperature_upstream_dirs:
  - "data/sampling_analysis_v1/temperature_sampling_low"
  - "data/sampling_analysis_v1/temperature_sampling"
perturbation_upstream_dirs:
  - "data/sampling_analysis_v1/perturbation_sampling_low"
  - "data/sampling_analysis_v1/perturbation_sampling"
output_dir: "data/sampling_analysis_v1/comparison/downstream/plots"
